### PR TITLE
fix(tdmpc): Add missing save_freq to tdmpc policy config

### PR DESCRIPTION
**Pull request by jackvial**
## What this does
Add missing `save_freq` key to `lerobot/configs/policy/tdmpc.yaml`

Without `save_freq` set I get the following error
```
Exception has occurred: MissingMandatoryValue
Missing mandatory value: training.save_freq
    full_key: training.save_freq
    object_type=dict
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: $FULL_KEY

The above exception was the direct cause of the following exception:

  File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 380, in evaluate_and_checkpoint_if_needed
    step % cfg.training.save_freq == 0
  File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 447, in train
    evaluate_and_checkpoint_if_needed(step + 1, is_online=False)
  File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 652, in train_cli
    train(
  File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 669, in <module>
```
Screenshot 2024-09-02 at 11 16 36 AM

## How it was tested
Set `save_freq` to 10 and ran training and confirmed I was no longer seeing the error and checkpoints were saved

Screenshot 2024-09-02 at 11 18 52 AM

Screenshot 2024-09-02 at 11 26 10 AM

## How to checkout & try? (for the reviewer)
- `pip install -e ."[xarm, test]"`
- Set `save_freq: 10` in `lerobot/lerobot/configs/policy/tdmpc.yaml`
- Run `python lerobot/scripts/train.py dataset_repo_id=lerobot/xarm_lift_medium policy=tdmpc env=xarm hydra.run.dir=outputs/train/tdmpc_xarm_lift_medium_0 hydra.job.name=tdmpc_xarm_lift_medium_0 device=cuda wandb.enable=true`
- Or run with `.vscode/launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Train",
            "type": "debugpy",
            "request": "launch",
            "program": "${workspaceFolder}/lerobot/scripts/train.py",
            "args": [
                "dataset_repo_id=lerobot/xarm_lift_medium",
                "policy=tdmpc",
                "env=xarm",
                "hydra.run.dir=outputs/train/tdmpc_xarm_lift_medium_0",
                "hydra.job.name=tdmpc_xarm_lift_medium_0",
                "device=cuda",
                "wandb.enable=true"
            ],
            "console": "integratedTerminal",
            "python": "${workspaceFolder}/venv/bin/python3.10",
        }
    ]
}
```

### CODE REVIEW

**Comment by alexander-soare** [comment]
Thanks for looking into this @jackvial 

> Without save_freq set I get the following error

Could you please include the command you run to get the error? I've trained tdmpc many times and don't run into it, so I want to see if you are launching the training differently.

**Comment by jackvial** [comment]
> Thanks for looking into this @jackvial
> 
> > Without save_freq set I get the following error
> 
> Could you please include the command you run to get the error? I've trained tdmpc many times and don't run into it, so I want to see if you are launching the training differently.

This is the command I get the error with
```
python lerobot/scripts/train.py dataset_repo_id=lerobot/xarm_lift_medium policy=tdmpc env=xarm hydra.run.dir=outputs/train/tdmpc_xarm_lift_medium_1 hydra.job.name=tdmpc_xarm_lift_medium_1 device=cuda wandb.enable=true
```

Full output
```
(venv) jack@jackml:~/code/rl/lerobot (main)$ python lerobot/scripts/train.py dataset_repo_id=lerobot/xarm_lift_medium policy=tdmpc env=xarm hydra.run.dir=outputs/train/tdmpc_xarm_lift_medium_1 hydra.job.name=tdmpc_xarm_lift_medium_1 device=cuda wandb.enable=true
INFO 2024-09-02 13:46:43 ts/train.py:244 {'dataset_repo_id': 'lerobot/xarm_lift_medium',
 'device': 'cuda',
 'env': {'action_dim': 4,
         'episode_length': 200,
         'fps': '${fps}',
         'gym': {'obs_type': 'pixels_agent_pos',
                 'render_mode': 'rgb_array',
                 'visualization_height': 384,
                 'visualization_width': 384},
         'image_size': 84,
         'name': 'xarm',
         'state_dim': 4,
         'task': 'XarmLift-v0'},
 'eval': {'batch_size': 1, 'n_episodes': 1, 'use_async_envs': False},
 'fps': 15,
 'policy': {'advantage_scaling': 3.0,
            'cem_iterations': 6,
            'consistency_coeff': 20.0,
            'discount': 0.9,
            'elite_weighting_temperature': 0.5,
            'expectile_weight': 0.9,
            'gaussian_mean_momentum': 0.1,
            'horizon': 5,
            'image_encoder_hidden_dim': 32,
            'input_normalization_modes': None,
            'input_shapes': {'observation.image': [3, 84, 84],
                             'observation.state': ['${env.state_dim}']},
            'latent_dim': 50,
            'max_random_shift_ratio': 0.0476,
            'max_std': 2.0,
            'min_std': 0.05,
            'mlp_dim': 512,
            'n_action_repeats': 2,
            'n_action_steps': 1,
            'n_elites': 50,
            'n_gaussian_samples': 512,
            'n_pi_samples': 51,
            'name': 'tdmpc',
            'output_normalization_modes': {'action': 'min_max'},
            'output_shapes': {'action': ['${env.action_dim}']},
            'pi_coeff': 0.5,
            'pretrained_model_path': None,
            'q_ensemble_size': 5,
            'reward_coeff': 0.5,
            'state_encoder_hidden_dim': 256,
            'target_model_momentum': 0.995,
            'temporal_decay_coeff': 0.5,
            'uncertainty_regularizer_coeff': 1.0,
            'use_mpc': True,
            'value_coeff': 0.1},
 'resume': False,
 'seed': 1,
 'training': {'batch_size': 256,
              'delta_timestamps': {'action': '[i / ${fps} for i in '
                                             'range(${policy.horizon})]',
                                   'next.reward': '[i / ${fps} for i in '
                                                  'range(${policy.horizon})]',
                                   'observation.image': '[i / ${fps} for i in '
                                                        'range(${policy.horizon} '
                                                        '+ 1)]',
                                   'observation.state': '[i / ${fps} for i in '
                                                        'range(${policy.horizon} '
                                                        '+ 1)]'},
              'do_online_rollout_async': False,
              'eval_freq': 5000,
              'grad_clip_norm': 10.0,
              'image_transforms': {'brightness': {'min_max': [0.8, 1.2],
                                                  'weight': 1},
                                   'contrast': {'min_max': [0.8, 1.2],
                                                'weight': 1},
                                   'enable': False,
                                   'hue': {'min_max': [-0.05, 0.05],
                                           'weight': 1},
                                   'max_num_transforms': 3,
                                   'random_order': False,
                                   'saturation': {'min_max': [0.5, 1.5],
                                                  'weight': 1},
                                   'sharpness': {'min_max': [0.8, 1.2],
                                                 'weight': 1}},
              'log_freq': 100,
              'lr': 0.0003,
              'num_workers': 4,
              'offline_steps': 50000,
              'online_buffer_capacity': 80000,
              'online_buffer_seed_size': 0,
              'online_env_seed': 10000,
              'online_rollout_batch_size': 1,
              'online_rollout_n_episodes': 1,
              'online_sampling_ratio': 0.5,
              'online_steps': 50000,
              'online_steps_between_rollouts': 50,
              'save_checkpoint': True,
              'save_freq': '???'},
 'use_amp': False,
 'video_backend': 'pyav',
 'wandb': {'disable_artifact': False,
           'enable': True,
           'notes': '',
           'project': 'lerobot'}}
Logs will be synced with wandb.
INFO 2024-09-02 13:46:45 n/logger.py:132 Track this run --> https://wandb.ai/jackvial/lerobot/runs/uxih155n
INFO 2024-09-02 13:46:45 ts/train.py:312 make_dataset
Fetching 806 files: 100%|████████████████████████████████████| 806/806 [00:00<00:00, 934.83it/s]
INFO 2024-09-02 13:46:48 ts/train.py:325 make_env
INFO 2024-09-02 13:46:48 tesupport.py:23 No OpenGL_accelerate module loaded: %s
INFO 2024-09-02 13:46:49 ts/train.py:328 make_policy
/home/jack/code/rl/lerobot/lerobot/scripts/train.py:338: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  grad_scaler = GradScaler(enabled=cfg.use_amp)
INFO 2024-09-02 13:46:49 on/logger.py:39 Output dir: outputs/train/tdmpc_xarm_lift_medium_1
INFO 2024-09-02 13:46:49 ts/train.py:349 cfg.env.task='XarmLift-v0'
INFO 2024-09-02 13:46:49 ts/train.py:350 cfg.training.offline_steps=50000 (50K)
INFO 2024-09-02 13:46:49 ts/train.py:351 cfg.training.online_steps=50000
INFO 2024-09-02 13:46:49 ts/train.py:352 offline_dataset.num_samples=20000 (20K)
INFO 2024-09-02 13:46:49 ts/train.py:353 offline_dataset.num_episodes=800
INFO 2024-09-02 13:46:49 ts/train.py:354 num_learnable_params=2734573 (3M)
INFO 2024-09-02 13:46:49 ts/train.py:355 num_total_params=5469162 (5M)
INFO 2024-09-02 13:46:49 ts/train.py:421 Start offline training on a fixed dataset
INFO 2024-09-02 13:46:53 ts/train.py:192 step:0 smpl:256 ep:10 epch:0.01 loss:4.325 grdn:23.122 lr:3.0e-04 updt_s:0.865 data_s:3.706
WARNING 2024-09-02 13:46:53 n/logger.py:236 WandB logging of key "advantage" was ignored as its type is not handled by this wrapper.
Error executing job with overrides: ['dataset_repo_id=lerobot/xarm_lift_medium', 'policy=tdmpc', 'env=xarm', 'device=cuda', 'wandb.enable=true']
Traceback (most recent call last):
  File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 652, in train_cli
    train(
  File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 447, in train
    evaluate_and_checkpoint_if_needed(step + 1, is_online=False)
  File "/home/jack/code/rl/lerobot/lerobot/scripts/train.py", line 380, in evaluate_and_checkpoint_if_needed
    step % cfg.training.save_freq == 0
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: training.save_freq
    full_key: training.save_freq
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: WARNING The new W&B backend becomes opt-out in version 0.18.0; try it out with `wandb.require("core")`! See https://wandb.me/wandb-core for more information.
Exception ignored in: <function VectorEnv.__del__ at 0x70c3b8d81240>
Traceback (most recent call last):
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/vector/vector_env.py", line 330, in __del__
    self.close()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/vector/vector_env.py", line 272, in close
    self.close_extras(**kwargs)
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/vector/sync_vector_env.py", line 217, in close_extras
    [env.close() for env in self.envs]
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/vector/sync_vector_env.py", line 217, in <listcomp>
    [env.close() for env in self.envs]
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/core.py", line 475, in close
    return self.env.close()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/core.py", line 475, in close
    return self.env.close()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gym_xarm/tasks/base.py", line 332, in close
    self.observation_renderer.close()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 714, in close
    viewer.close()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 277, in close
    self.free()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 188, in free
    self.opengl_context.free()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 123, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE,
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x70c3b08b55c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x70c3b29970c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x70c3b29970c0>,
                <OpenGL._opaque.EGLContext_pointer object at 0x70c3b29979c0>,
        ),
        result = 0
)
Exception ignored in: <function OffScreenViewer.__del__ at 0x70c3b29d75b0>
Traceback (most recent call last):
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 191, in __del__
    self.free()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 188, in free
    self.opengl_context.free()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 123, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE,
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x70c3b08b55c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x70c3b29970c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x70c3b29970c0>,
                <OpenGL._opaque.EGLContext_pointer object at 0x70c3b29979c0>,
        ),
        result = 0
)
Exception ignored in: <function GLContext.__del__ at 0x70c3b08af910>
Traceback (most recent call last):
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 130, in __del__
    self.free()
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 123, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE,
  File "/home/jack/code/rl/lerobot/venv/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
        err = EGL_NOT_INITIALIZED,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x70c3b08b55c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x70c3b29970c0>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x70c3b29970c0>,
                <OpenGL._opaque.EGLContext_pointer object at 0x70c3b29979c0>,
        ),
        result = 0
)
```

**Review by alexander-soare — APPROVED** [review]

**Comment by alexander-soare** [comment]
Okay that's my bad. I'm so used to using my bash script to run it that I forgot I have save_freq in there every time I run it. Approved!

**Comment by alexander-soare** [comment]
Merged!

**Comment by jackvial** [comment]
> Okay that's my bad. I'm so used to using my bash script to run it that I forgot I have save_freq in there every time I run it. Approved!

I often do the same, it's an easy thing to miss!

**Pull request merged**
