### PR TITLE
OXE rlds data format to hg lerobot format

### PR DESCRIPTION
**Pull request by youliangtan**
## What this does
A generic implementation to convert existing [OXE dataset](https://github.com/google-deepmind/open_x_embodiment (OXE)) (RTX)  which is in standard RLDS to Lerobot dataformat.

The current open-x-embodiment RLDS dataset is still "messy". Here, the standardization across all dataset is done by applying `datasets/push_dataset_to_hub/oxe/transforms.py` and `datasets/push_dataset_to_hub/oxe/configs.py` (e.g. similar to [octo](https://octo-models.github.io/) and [openvla](https://openvla.github.io/)). Despite this, user still has the flexibility to convert existing "non-oxe" rlds format to lerobot.

## Example 

To upload a sample dataset `austin_buds_dataset_converted_externally_to_rlds`, run:
```bash
python lerobot/scripts/push_dataset_to_hub.py \
--raw-dir /hdd/tensorflow_datasets/austin_buds_dataset_converted_externally_to_rlds/0.1.0/ \
--repo-id youliangtan/austin_buds_dataset_converted_externally_to_rlds_to_hg  \
--raw-format oxe_rlds.austin_buds_dataset_converted_externally_to_rlds   # format is in: "oxe_rlds.<OXE_DATASET_NAME>"
```

The official <OXE_DATASET_NAME> is listed [here](https://docs.google.com/spreadsheets/d/1rPBD77tk60AEIGZrGSODwyyzs5FgCU9Uz3h-3_t2A9g/edit?gid=0#gid=0&range=S:S).

The uploaded data is located here in: https://huggingface.co/datasets/youliangtan/austin_buds_dataset_converted_externally_to_rlds_to_hg

## Sample OXE dataset on hg:
- `youliangtan/sampled_bridge_data_v2` (only 5 trajectories as example)
- `youliangtan/austin_buds_dataset_converted_externally_to_rlds_to_hg`
- `youliangtan/nyu_franka_play_dataset_converted_externally_to_rlds_to_hg`
- `youliangtan/cmu_stretch_to_hg`
- `youliangtan/droid_100_to_hg` (first 100 trajectories from droid data)
- `youliangtan/sampled_google_robot_ds` (only 5 trajectories as example)

Try visualize data locally:
```bash
python lerobot/scripts/visualize_dataset.py     --repo-id youliangtan/sampled_bridge_data_v2     --episode-index 2
```

## TODO:
- test with more datasets
- clean up impl

## Open questions
- The current impl uses default T5 language encoder, with some default kwargs
- make `MultiLeRobotDataset` support custom sampling weights.

### CODE REVIEW

**Comment by youliangtan** [comment]
Also, I would like to check with the hugging face team. Is there any further plan to support the on-browser visualization of the lerobot dataset's (parquet file/videos), without needing the user to download the dataset? :thinking:

**Comment by Cadene** [comment]
> Also, I would like to check with the hugging face team. Is there any further plan to support the on-browser visualization of the lerobot dataset's (parquet file/videos), without needing the user to download the dataset? 🤔

@youliangtan @tlpss Yes! We are currently working on this. In particular, we noticed that our video encoding format is only supported by  google-chrome, and not in other common browsers like firefox and safari. We are currently benchmarking other options. Then it will be easy to visualize the datasets on the hub directly ;)

**Comment by Cadene** [comment]
@youliangtan Out of curiosity, do you have higher resolution videos? Also the `fps` looks a bit off in the video (frames are switching slowly). Is it expected? Thanks!

https://github.com/huggingface/lerobot/assets/4681518/ef7bee3d-d64a-4d34-81c3-2c5d1a67f979

https://github.com/huggingface/lerobot/assets/4681518/da3c518d-fc8e-41fa-bb2f-06f772875811

**Comment by youliangtan** [comment]
I have updated the `austin_buds` dataset to 20fps via the `--fps` arg. Control Frequency for all OXE datasets is specified [here](https://docs.google.com/spreadsheets/d/1rPBD77tk60AEIGZrGSODwyyzs5FgCU9Uz3h-3_t2A9g/edit?gid=0#gid=0&range=R:R).

https://github.com/huggingface/lerobot/assets/32189404/3583cab8-a702-4ce5-be3b-19ddca7326c2

Also, I added the `language_instruction` field, and uses T5-small as the default lang tokenizer (similar to [octo](https://github.com/octo-models/octo/blob/5eaa5c6960398925ae6f52ed072d843d2f3ecb0b/scripts/configs/octo_pretrain_config.py#L140-L145)). i also ignore it in the `compute_stats` process. The implementation might look abit sketchy, feedback is appreciated. =)

**Comment by Cadene** [comment]
@youliangtan Sorry for the wait. We are going to review this PR soon with @michel-aractingi .
Best

**Comment by youliangtan** [comment]
Thanks for reviewing it. I made some changes such that each officially supported open-x dataset should have a "config" to help standardize the RLDS format (used in Octo and OpenVLA) before converting to the LeRobot format.

Currently, this work still requires cleanup and more tests across all OXE datasets. Some high-level comments would be appreciated before I start converting all existing OXE datasets. :pray: 

Additionally, I noticed that the `Compute mean, min, max: ...` process is taking a considerable amount of time (90% of the conversion time). I can open another GitHub issue to address this.

**Comment by michel-aractingi** [comment]
Closing this PR and the work here has been merged in #354 . Thank you @youliangtan!

**Pull request closed without merging**
