### PR TITLE
Add support for Windows

### PR DESCRIPTION
**Pull request by brainwavecoder9**
## What this does
Windows uses COM ports not what is expected for Linux/Mac. This commit adds support for Windows OS. It does this by: 
 - checking to see if OS is Windows, or other
 - if Windows, use a new process
 - if other, use existing process 

There is a dependency (`pyserial`) but it is already in the environment so no changes there. Once the port is identified it can be added to the `.yaml` the same as it is today. Although it will be referenced differently (e.g., `COM7` vs. `/dev/ttyACM`) the rest of the functionality still works.

## How it was tested
Successful in Windows environment, and theoretically won't affect others, but does need to be confirmed before merge.

## How to checkout & try? (for the reviewer)
No change to [existing process](https://github.com/huggingface/lerobot/blob/main/examples/10_use_so100.md#configure-the-motors). To use, simply execute the existing script, e.g., `python lerobot/scripts/find_motors_bus_port.py`

### CODE REVIEW

**Comment by Cadene** [comment]
Looks good to me! Thanks for the improvements to print + comments ;)
Running tests and merging.

**Comment by Cadene** [comment]
Style check failing. Run our pre-commit ;)
```
pre-commit run --all-files
```
https://github.com/huggingface/lerobot/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr

**Comment by brainwavecoder9** [comment]
Oh you mean I'm actually supposed to follow the instructions for contributing 😅

I thought "no way this won't pass" but here we are... updates made!

**Comment by brainwavecoder9** [comment]
OK @Cadene this one isn't on me my test passed 😄 

System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241101-143253-utc.log'
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.320.0/_diag/Worker_20241101-143253-utc.log'

If this is something you want me to have a look at let me know, I've done lots of infra.

**Review by Cadene — APPROVED** [review]
Thanks!

**Comment by Cadene** [comment]
@brainwavecoder9 If you find any other compatibility issue, please let me know. I will be more reactive this time ;)

**Pull request merged**
